Repository communitybridge/easycla-contributor-console, pull requests merged in 2021-01, with the labels that each got.

#168 V2 - Identify CLA Manager - Focus is moved out of Identify CLA Manager popup when hit on TAB key
  src/app/modules/corporate-contributor/component/identify-cla-manager-modal/identify-cla-manager-modal.component.html
  src/app/modules/corporate-contributor/component/identify-cla-manager-modal/identify-cla-manager-modal.component.scss
  src/app/modules/corporate-contributor/component/identify-cla-manager-modal/identify-cla-manager-modal.component.ts
Labels: bug

#169 Provide link to documentation faq when email is incorrect
  src/app/modules/corporate-contributor/component/identify-cla-manager-modal/identify-cla-manager-modal.component.html
  src/index.html
Labels: bug

#170 [2351] restrict clear bit API call when website not valid
  src/app/modules/corporate-contributor/component/add-company-modal/add-company-modal.component.ts
Labels: bug

#174 Changed base URL's from enviroment file to SSM
  src/app/core/services/cla-contributor.service.ts
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
  src/environments/environment.staging.ts
  src/environments/environment.ts
Labels: bug

#175 CCLA is not enabled to this project please contact to your administrator." error message is shown for every request on contributor console
  edge/security-headers.js
Labels: bug

#178 Stakeholder feedback: Add Signing Entity Name in Create New organisation a. Integrated search organisation API changes
  src/app/core/models/organization.ts
  src/app/core/services/cla-contributor.service.ts
  src/app/modules/corporate-contributor/component/add-company-modal/add-company-modal.component.html
  src/app/modules/corporate-contributor/component/add-company-modal/add-company-modal.component.scss
  src/app/modules/corporate-contributor/component/add-company-modal/add-company-modal.component.ts
  src/app/modules/corporate-contributor/component/configure-cla-manager-modal/configure-cla-manager-modal.component.ts
  src/app/modules/corporate-contributor/component/identify-cla-manager-modal/identify-cla-manager-modal.component.ts
  src/app/modules/corporate-contributor/container/corporate-dashboard/corporate-dashboard.component.html
  src/app/modules/corporate-contributor/container/corporate-dashboard/corporate-dashboard.component.scss
  src/app/modules/corporate-contributor/container/corporate-dashboard/corporate-dashboard.component.ts
Labels: enhancement

#179 Changed company name and entity name regex validation and other minor bugs
  src/app/config/app-settings.ts
  src/app/modules/corporate-contributor/component/add-company-modal/add-company-modal.component.html
  src/app/modules/corporate-contributor/component/add-company-modal/add-company-modal.component.ts
  src/app/modules/corporate-contributor/container/corporate-dashboard/corporate-dashboard.component.ts
Labels: bug

#185 Browser suggestion on Search Org. hides the suggestion from Org services
  src/app/modules/corporate-contributor/component/add-company-modal/add-company-modal.component.html
  src/app/modules/corporate-contributor/component/identify-cla-manager-modal/identify-cla-manager-modal.component.html
  src/app/modules/corporate-contributor/container/corporate-dashboard/corporate-dashboard.component.html
Labels: bug

#186 Roles is not assigned to the newly created user when he navigated to corporate console post verifying email and roles setting is complete
  src/app/config/app-settings.ts
  src/app/core/services/cla-contributor.service.ts
  src/app/modules/corporate-contributor/component/configure-cla-manager-modal/configure-cla-manager-modal.component.html
  src/app/modules/corporate-contributor/component/configure-cla-manager-modal/configure-cla-manager-modal.component.ts
  src/app/modules/corporate-contributor/container/corporate-dashboard/corporate-dashboard.component.ts
  src/styles.scss
Labels: enhancement

#188 [Snyk] Upgrade aws-sdk from 2.736.0 to 2.820.0
  package.json
  yarn.lock
Labels: do-not-merge

#200 Not able to create new organisation in contributor console
  src/app/modules/corporate-contributor/component/configure-cla-manager-modal/configure-cla-manager-modal.component.ts
Labels: bug

#201 Added signingEntityCompanyId as queryparam while redirecting to the corporate console
  src/app/modules/corporate-contributor/component/configure-cla-manager-modal/configure-cla-manager-modal.component.ts
Labels: enhancement
